// ISO 3166-1 alpha-2 country codes with their Spanish names.
//
// Generated once with Node's `Intl.DisplayNames` (locale `es`) instead of
// fetching restcountries.com at runtime: that call was blocked by CORS, added a
// third-party dependency to a form field, and stored the English country name
// as the value. The stored value is now the ISO code; the Spanish name is only
// a presentation detail that lives here.
export interface CountryOption {
  isoCode: string; // ISO 3166-1 alpha-2, e.g. "ES"
  nameEs: string; // e.g. "España"
}

// Pre-sorted by `nameEs` with `localeCompare('es')` at generation time, so no
// consumer has to re-sort 249 entries on every render.
export const COUNTRIES: CountryOption[] = [
  { isoCode: 'AF', nameEs: 'Afganistán' },
  { isoCode: 'AL', nameEs: 'Albania' },
  { isoCode: 'DE', nameEs: 'Alemania' },
  { isoCode: 'AD', nameEs: 'Andorra' },
  { isoCode: 'AO', nameEs: 'Angola' },
  { isoCode: 'AI', nameEs: 'Anguila' },
  { isoCode: 'AQ', nameEs: 'Antártida' },
  { isoCode: 'AG', nameEs: 'Antigua y Barbuda' },
  { isoCode: 'SA', nameEs: 'Arabia Saudí' },
  { isoCode: 'DZ', nameEs: 'Argelia' },
  { isoCode: 'AR', nameEs: 'Argentina' },
  { isoCode: 'AM', nameEs: 'Armenia' },
  { isoCode: 'AW', nameEs: 'Aruba' },
  { isoCode: 'AU', nameEs: 'Australia' },
  { isoCode: 'AT', nameEs: 'Austria' },
  { isoCode: 'AZ', nameEs: 'Azerbaiyán' },
  { isoCode: 'BS', nameEs: 'Bahamas' },
  { isoCode: 'BD', nameEs: 'Bangladés' },
  { isoCode: 'BB', nameEs: 'Barbados' },
  { isoCode: 'BH', nameEs: 'Baréin' },
  { isoCode: 'BE', nameEs: 'Bélgica' },
  { isoCode: 'BZ', nameEs: 'Belice' },
  { isoCode: 'BJ', nameEs: 'Benín' },
  { isoCode: 'BM', nameEs: 'Bermudas' },
  { isoCode: 'BY', nameEs: 'Bielorrusia' },
  { isoCode: 'BO', nameEs: 'Bolivia' },
  { isoCode: 'BA', nameEs: 'Bosnia y Herzegovina' },
  { isoCode: 'BW', nameEs: 'Botsuana' },
  { isoCode: 'BR', nameEs: 'Brasil' },
  { isoCode: 'BN', nameEs: 'Brunéi' },
  { isoCode: 'BG', nameEs: 'Bulgaria' },
  { isoCode: 'BF', nameEs: 'Burkina Faso' },
  { isoCode: 'BI', nameEs: 'Burundi' },
  { isoCode: 'BT', nameEs: 'Bután' },
  { isoCode: 'CV', nameEs: 'Cabo Verde' },
  { isoCode: 'KH', nameEs: 'Camboya' },
  { isoCode: 'CM', nameEs: 'Camerún' },
  { isoCode: 'CA', nameEs: 'Canadá' },
  { isoCode: 'BQ', nameEs: 'Caribe neerlandés' },
  { isoCode: 'QA', nameEs: 'Catar' },
  { isoCode: 'TD', nameEs: 'Chad' },
  { isoCode: 'CZ', nameEs: 'Chequia' },
  { isoCode: 'CL', nameEs: 'Chile' },
  { isoCode: 'CN', nameEs: 'China' },
  { isoCode: 'CY', nameEs: 'Chipre' },
  { isoCode: 'VA', nameEs: 'Ciudad del Vaticano' },
  { isoCode: 'CO', nameEs: 'Colombia' },
  { isoCode: 'KM', nameEs: 'Comoras' },
  { isoCode: 'CG', nameEs: 'Congo' },
  { isoCode: 'KP', nameEs: 'Corea del Norte' },
  { isoCode: 'KR', nameEs: 'Corea del Sur' },
  { isoCode: 'CI', nameEs: 'Costa de Marfil' },
  { isoCode: 'CR', nameEs: 'Costa Rica' },
  { isoCode: 'HR', nameEs: 'Croacia' },
  { isoCode: 'CU', nameEs: 'Cuba' },
  { isoCode: 'CW', nameEs: 'Curazao' },
  { isoCode: 'DK', nameEs: 'Dinamarca' },
  { isoCode: 'DM', nameEs: 'Dominica' },
  { isoCode: 'EC', nameEs: 'Ecuador' },
  { isoCode: 'EG', nameEs: 'Egipto' },
  { isoCode: 'SV', nameEs: 'El Salvador' },
  { isoCode: 'AE', nameEs: 'Emiratos Árabes Unidos' },
  { isoCode: 'ER', nameEs: 'Eritrea' },
  { isoCode: 'SK', nameEs: 'Eslovaquia' },
  { isoCode: 'SI', nameEs: 'Eslovenia' },
  { isoCode: 'ES', nameEs: 'España' },
  { isoCode: 'US', nameEs: 'Estados Unidos' },
  { isoCode: 'EE', nameEs: 'Estonia' },
  { isoCode: 'SZ', nameEs: 'Esuatini' },
  { isoCode: 'ET', nameEs: 'Etiopía' },
  { isoCode: 'PH', nameEs: 'Filipinas' },
  { isoCode: 'FI', nameEs: 'Finlandia' },
  { isoCode: 'FJ', nameEs: 'Fiyi' },
  { isoCode: 'FR', nameEs: 'Francia' },
  { isoCode: 'GA', nameEs: 'Gabón' },
  { isoCode: 'GM', nameEs: 'Gambia' },
  { isoCode: 'GE', nameEs: 'Georgia' },
  { isoCode: 'GH', nameEs: 'Ghana' },
  { isoCode: 'GI', nameEs: 'Gibraltar' },
  { isoCode: 'GD', nameEs: 'Granada' },
  { isoCode: 'GR', nameEs: 'Grecia' },
  { isoCode: 'GL', nameEs: 'Groenlandia' },
  { isoCode: 'GP', nameEs: 'Guadalupe' },
  { isoCode: 'GU', nameEs: 'Guam' },
  { isoCode: 'GT', nameEs: 'Guatemala' },
  { isoCode: 'GF', nameEs: 'Guayana Francesa' },
  { isoCode: 'GG', nameEs: 'Guernesey' },
  { isoCode: 'GN', nameEs: 'Guinea' },
  { isoCode: 'GQ', nameEs: 'Guinea Ecuatorial' },
  { isoCode: 'GW', nameEs: 'Guinea-Bisáu' },
  { isoCode: 'GY', nameEs: 'Guyana' },
  { isoCode: 'HT', nameEs: 'Haití' },
  { isoCode: 'HN', nameEs: 'Honduras' },
  { isoCode: 'HU', nameEs: 'Hungría' },
  { isoCode: 'IN', nameEs: 'India' },
  { isoCode: 'ID', nameEs: 'Indonesia' },
  { isoCode: 'IQ', nameEs: 'Irak' },
  { isoCode: 'IR', nameEs: 'Irán' },
  { isoCode: 'IE', nameEs: 'Irlanda' },
  { isoCode: 'BV', nameEs: 'Isla Bouvet' },
  { isoCode: 'IM', nameEs: 'Isla de Man' },
  { isoCode: 'CX', nameEs: 'Isla de Navidad' },
  { isoCode: 'NF', nameEs: 'Isla Norfolk' },
  { isoCode: 'IS', nameEs: 'Islandia' },
  { isoCode: 'AX', nameEs: 'Islas Aland' },
  { isoCode: 'KY', nameEs: 'Islas Caimán' },
  { isoCode: 'CC', nameEs: 'Islas Cocos' },
  { isoCode: 'CK', nameEs: 'Islas Cook' },
  { isoCode: 'FO', nameEs: 'Islas Feroe' },
  { isoCode: 'GS', nameEs: 'Islas Georgia del Sur y Sandwich del Sur' },
  { isoCode: 'HM', nameEs: 'Islas Heard y McDonald' },
  { isoCode: 'FK', nameEs: 'Islas Malvinas' },
  { isoCode: 'MP', nameEs: 'Islas Marianas del Norte' },
  { isoCode: 'MH', nameEs: 'Islas Marshall' },
  { isoCode: 'UM', nameEs: 'Islas menores alejadas de EE. UU.' },
  { isoCode: 'PN', nameEs: 'Islas Pitcairn' },
  { isoCode: 'SB', nameEs: 'Islas Salomón' },
  { isoCode: 'TC', nameEs: 'Islas Turcas y Caicos' },
  { isoCode: 'VG', nameEs: 'Islas Vírgenes Británicas' },
  { isoCode: 'VI', nameEs: 'Islas Vírgenes de EE. UU.' },
  { isoCode: 'IL', nameEs: 'Israel' },
  { isoCode: 'IT', nameEs: 'Italia' },
  { isoCode: 'JM', nameEs: 'Jamaica' },
  { isoCode: 'JP', nameEs: 'Japón' },
  { isoCode: 'JE', nameEs: 'Jersey' },
  { isoCode: 'JO', nameEs: 'Jordania' },
  { isoCode: 'KZ', nameEs: 'Kazajistán' },
  { isoCode: 'KE', nameEs: 'Kenia' },
  { isoCode: 'KG', nameEs: 'Kirguistán' },
  { isoCode: 'KI', nameEs: 'Kiribati' },
  { isoCode: 'KW', nameEs: 'Kuwait' },
  { isoCode: 'LA', nameEs: 'Laos' },
  { isoCode: 'LS', nameEs: 'Lesoto' },
  { isoCode: 'LV', nameEs: 'Letonia' },
  { isoCode: 'LB', nameEs: 'Líbano' },
  { isoCode: 'LR', nameEs: 'Liberia' },
  { isoCode: 'LY', nameEs: 'Libia' },
  { isoCode: 'LI', nameEs: 'Liechtenstein' },
  { isoCode: 'LT', nameEs: 'Lituania' },
  { isoCode: 'LU', nameEs: 'Luxemburgo' },
  { isoCode: 'MK', nameEs: 'Macedonia del Norte' },
  { isoCode: 'MG', nameEs: 'Madagascar' },
  { isoCode: 'MY', nameEs: 'Malasia' },
  { isoCode: 'MW', nameEs: 'Malaui' },
  { isoCode: 'MV', nameEs: 'Maldivas' },
  { isoCode: 'ML', nameEs: 'Mali' },
  { isoCode: 'MT', nameEs: 'Malta' },
  { isoCode: 'MA', nameEs: 'Marruecos' },
  { isoCode: 'MQ', nameEs: 'Martinica' },
  { isoCode: 'MU', nameEs: 'Mauricio' },
  { isoCode: 'MR', nameEs: 'Mauritania' },
  { isoCode: 'YT', nameEs: 'Mayotte' },
  { isoCode: 'MX', nameEs: 'México' },
  { isoCode: 'FM', nameEs: 'Micronesia' },
  { isoCode: 'MD', nameEs: 'Moldavia' },
  { isoCode: 'MC', nameEs: 'Mónaco' },
  { isoCode: 'MN', nameEs: 'Mongolia' },
  { isoCode: 'ME', nameEs: 'Montenegro' },
  { isoCode: 'MS', nameEs: 'Montserrat' },
  { isoCode: 'MZ', nameEs: 'Mozambique' },
  { isoCode: 'MM', nameEs: 'Myanmar (Birmania)' },
  { isoCode: 'NA', nameEs: 'Namibia' },
  { isoCode: 'NR', nameEs: 'Nauru' },
  { isoCode: 'NP', nameEs: 'Nepal' },
  { isoCode: 'NI', nameEs: 'Nicaragua' },
  { isoCode: 'NE', nameEs: 'Níger' },
  { isoCode: 'NG', nameEs: 'Nigeria' },
  { isoCode: 'NU', nameEs: 'Niue' },
  { isoCode: 'NO', nameEs: 'Noruega' },
  { isoCode: 'NC', nameEs: 'Nueva Caledonia' },
  { isoCode: 'NZ', nameEs: 'Nueva Zelanda' },
  { isoCode: 'OM', nameEs: 'Omán' },
  { isoCode: 'NL', nameEs: 'Países Bajos' },
  { isoCode: 'PK', nameEs: 'Pakistán' },
  { isoCode: 'PW', nameEs: 'Palaos' },
  { isoCode: 'PA', nameEs: 'Panamá' },
  { isoCode: 'PG', nameEs: 'Papúa Nueva Guinea' },
  { isoCode: 'PY', nameEs: 'Paraguay' },
  { isoCode: 'PE', nameEs: 'Perú' },
  { isoCode: 'PF', nameEs: 'Polinesia Francesa' },
  { isoCode: 'PL', nameEs: 'Polonia' },
  { isoCode: 'PT', nameEs: 'Portugal' },
  { isoCode: 'PR', nameEs: 'Puerto Rico' },
  { isoCode: 'HK', nameEs: 'RAE de Hong Kong (China)' },
  { isoCode: 'MO', nameEs: 'RAE de Macao (China)' },
  { isoCode: 'GB', nameEs: 'Reino Unido' },
  { isoCode: 'CF', nameEs: 'República Centroafricana' },
  { isoCode: 'CD', nameEs: 'República Democrática del Congo' },
  { isoCode: 'DO', nameEs: 'República Dominicana' },
  { isoCode: 'RE', nameEs: 'Reunión' },
  { isoCode: 'RW', nameEs: 'Ruanda' },
  { isoCode: 'RO', nameEs: 'Rumanía' },
  { isoCode: 'RU', nameEs: 'Rusia' },
  { isoCode: 'EH', nameEs: 'Sáhara Occidental' },
  { isoCode: 'WS', nameEs: 'Samoa' },
  { isoCode: 'AS', nameEs: 'Samoa Americana' },
  { isoCode: 'BL', nameEs: 'San Bartolomé' },
  { isoCode: 'KN', nameEs: 'San Cristóbal y Nieves' },
  { isoCode: 'SM', nameEs: 'San Marino' },
  { isoCode: 'MF', nameEs: 'San Martín' },
  { isoCode: 'PM', nameEs: 'San Pedro y Miquelón' },
  { isoCode: 'VC', nameEs: 'San Vicente y las Granadinas' },
  { isoCode: 'SH', nameEs: 'Santa Elena' },
  { isoCode: 'LC', nameEs: 'Santa Lucía' },
  { isoCode: 'ST', nameEs: 'Santo Tomé y Príncipe' },
  { isoCode: 'SN', nameEs: 'Senegal' },
  { isoCode: 'RS', nameEs: 'Serbia' },
  { isoCode: 'SC', nameEs: 'Seychelles' },
  { isoCode: 'SL', nameEs: 'Sierra Leona' },
  { isoCode: 'SG', nameEs: 'Singapur' },
  { isoCode: 'SX', nameEs: 'Sint Maarten' },
  { isoCode: 'SY', nameEs: 'Siria' },
  { isoCode: 'SO', nameEs: 'Somalia' },
  { isoCode: 'LK', nameEs: 'Sri Lanka' },
  { isoCode: 'ZA', nameEs: 'Sudáfrica' },
  { isoCode: 'SD', nameEs: 'Sudán' },
  { isoCode: 'SS', nameEs: 'Sudán del Sur' },
  { isoCode: 'SE', nameEs: 'Suecia' },
  { isoCode: 'CH', nameEs: 'Suiza' },
  { isoCode: 'SR', nameEs: 'Surinam' },
  { isoCode: 'SJ', nameEs: 'Svalbard y Jan Mayen' },
  { isoCode: 'TH', nameEs: 'Tailandia' },
  { isoCode: 'TW', nameEs: 'Taiwán' },
  { isoCode: 'TZ', nameEs: 'Tanzania' },
  { isoCode: 'TJ', nameEs: 'Tayikistán' },
  { isoCode: 'IO', nameEs: 'Territorio Británico del Océano Índico' },
  { isoCode: 'TF', nameEs: 'Territorios Australes Franceses' },
  { isoCode: 'PS', nameEs: 'Territorios Palestinos' },
  { isoCode: 'TL', nameEs: 'Timor-Leste' },
  { isoCode: 'TG', nameEs: 'Togo' },
  { isoCode: 'TK', nameEs: 'Tokelau' },
  { isoCode: 'TO', nameEs: 'Tonga' },
  { isoCode: 'TT', nameEs: 'Trinidad y Tobago' },
  { isoCode: 'TN', nameEs: 'Túnez' },
  { isoCode: 'TM', nameEs: 'Turkmenistán' },
  { isoCode: 'TR', nameEs: 'Turquía' },
  { isoCode: 'TV', nameEs: 'Tuvalu' },
  { isoCode: 'UA', nameEs: 'Ucrania' },
  { isoCode: 'UG', nameEs: 'Uganda' },
  { isoCode: 'UY', nameEs: 'Uruguay' },
  { isoCode: 'UZ', nameEs: 'Uzbekistán' },
  { isoCode: 'VU', nameEs: 'Vanuatu' },
  { isoCode: 'VE', nameEs: 'Venezuela' },
  { isoCode: 'VN', nameEs: 'Vietnam' },
  { isoCode: 'WF', nameEs: 'Wallis y Futuna' },
  { isoCode: 'YE', nameEs: 'Yemen' },
  { isoCode: 'DJ', nameEs: 'Yibuti' },
  { isoCode: 'ZM', nameEs: 'Zambia' },
  { isoCode: 'ZW', nameEs: 'Zimbabue' },
];

// Built once at module load: the lookup runs on every render of any list that
// shows a country, and a linear `.find()` over 249 entries per call adds up.
// A Map, not a plain object: the code comes from legacy free-text data, so a
// value like "toString" would otherwise resolve to an Object.prototype member
// typed as string and end up rendered as a React child.
const COUNTRY_NAMES_BY_CODE = new Map(
  COUNTRIES.map(({ isoCode, nameEs }) => [isoCode, nameEs]),
);

// Returns `undefined` for unknown or missing codes so callers can decide what
// to render (placeholder, empty state, the raw legacy value...).
export const getCountryName = (isoCode?: string): string | undefined => (
  isoCode ? COUNTRY_NAMES_BY_CODE.get(isoCode) : undefined
);
